# Generated by Django 4.2.4 on 2023-08-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='barang_merk',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='barang',
            name='barang_nama',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='harga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petugas',
            name='petugas_tgl_lhr',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='petugas_relasi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='penjualan_app.petugas'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='transaksi_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='transaksi_tgl',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='barang_stok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(default='user@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='petugas_email',
            field=models.EmailField(default='user@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='barang_relasi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='penjualan_app.barang'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='customer_relasi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='penjualan_app.customer'),
        ),
    ]
