# Generated by Django 4.2.4 on 2023-08-24 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan_app', '0002_barang_barang_merk_barang_barang_nama_barang_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='barang_relasi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='penjualan_app.barang'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='customer_relasi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='penjualan_app.customer'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='petugas_relasi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='penjualan_app.petugas'),
        ),
    ]
